tag_names = ["path", "loss"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/{MODE}" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }
columns = { vf = "10 * vf" }  # convert from units of σ = 10mV to mV

[plots.__matrix__]
x = ["vf", "rf"]

[[plots.__include__]]
name = { __eval__ = "f'{x}'" }
func = "displot"
# groupby = ["loss"]
col = "cell_type"
col_order = ["PYR", "PV", "SST", "VIP"]
# hue_order = ["PV", "SST", "VIP"]
row = "loss"
estimator = "mean"
element = "step"
fill = false
common_bins = false
common_norm = false
stat = "density"
# outliers = [0.001, 1]
# outliers = [0.01, 1]
# grid = "yzero"
# height = "paper"
height = 1.2
aspect = 1.1
rc_params = "paper"
title_verbosity = 0
# tight_layout = true
facet_kws = { sharey = false, sharex = false }
# facet_kws = { sharey = false }
# errordim = "instance_idx"
# errorbar = "se"
# err_kws = { linewidth = 0.5 }

[plots.__include__.mapping]
loss = "Loss"
cell_type = "Cell type"
vf = "Baseline synaptic input (mV)"
rf = "Baseline firing rate (Hz)"

[[plots.__include__]]
x = "rf"
log_scale = true

