tag_names = ["kind", "loss"]

[dataframes.__matrix__]
kind = [{ __environ__ = "MODE" }, { __format__ = "{MODE}_reclinear_PV" }, { __format__ = "{MODE}_reclinear_SST" }, { __format__ = "{MODE}_reclinear_VIP" }]
loss = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "fits" }, pattern = "*.pt", stem = true, indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
func = ["niarb.io", "load_data"]
paths = { __eval__ = "f'runs/{kind}/{loss}.pkl'" }
query = "N == 10 and distance > 15 and distance < 75"
pivot_table = { index = ["kind", "loss", "instance_idx", "cell_type", "density"], columns = "holo_osi", values = "dr" }
columns = { ddr = "high - low" }

[plots]
__ignore__ = ["subset"]

[plots.__matrix__]
subset = ["all", "PYR"]

[[plots.__include__]]
name = { __eval__ = "subset" }
func = "catplot"
kind = "bar"
y = "ddr"
col = "loss"
grid = "yzero"
height = "paper"
rc_params = "paper"
title_verbosity = 0
legend_title = false
errorbar = "se"

[plots.__include__.mapping]
# dr = "Response (ΔF/F)"
# distance = 'Distance ($\mu$m)'
# rel_ori = '$\Delta$ ori. pref. (deg)'
ddr = "Cotuned - Untuned (ΔF/F)"
cell_type = "Cell type"
density = "Density"
# holo_osi = "Ens. Tuning"
kind = "Rectified linear cell type"

[plots.__include__.replace]
spreadout = "Diffuse"
compact = "Compact"
# low = "Untuned"
# high = "Cotuned"
numerical = "None"
numerical_reclinear_PV = "PV"
numerical_reclinear_SST = "SST"
numerical_reclinear_VIP = "VIP"
analytical = "None"
analytical_reclinear_PV = "PV"
analytical_reclinear_SST = "SST"
analytical_reclinear_VIP = "VIP"

[[plots.__include__]]
subset = "all"
x = "density"
order = ["spreadout", "compact"]
hue = "kind"
hue_order = [{ __environ__ = "MODE" }, { __format__ = "{MODE}_reclinear_PV" }, { __format__ = "{MODE}_reclinear_SST" }, { __format__ = "{MODE}_reclinear_VIP" }]
row = "cell_type"
row_order = ["PYR", "PV", "SST", "VIP"]
aspect = 1.5
sharey = false

[[plots.__include__]]
subset = "PYR"
query = "cell_type == 'PYR'"
x = "kind"
order = [{ __environ__ = "MODE" }, { __format__ = "{MODE}_reclinear_PV" }, { __format__ = "{MODE}_reclinear_SST" }, { __format__ = "{MODE}_reclinear_VIP" }]
row = "density"
row_order = ["spreadout", "compact"]
aspect = 1.25
sharey = "col"
statannot = true
statannot_kws = { kind = "1samp", test = "wilcoxon", test_kws = { alternative = "less" } }

# grid = { __const__ = "None" }
# facet_kws = {}
# tick_params = { axis = "x", bottom = false, labeltop = true, labelbottom = false }
# tick_params = { axis = "x", labelrotation = 30 }
# despine = { bottom = true, top = false }
# spine_positions = { top = "zero" }
# statannot = true
# statannot_kws = { test = "ttest_ind", test_kws = { alternative = "greater", equal_var = false, permutations = 999999 } }

