tag_names = ["path", "loss"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/{MODE}_more" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }

[plots]
__ignore__ = ["axes"]

[plots.__matrix__]
axes = ["space_ori", "ori"]

[[plots.__include__]]
name = { __eval__ = "f'resp_{axes}'" }
groupby = "perturbed_cell_type"
func = "relplot"
kind = "line"
y = "dr"
col = "loss"
row = "cell_type"
row_order = ["PYR", "PV", "SST", "VIP"]
grid = "yzero"
height = 2
aspect = 1
color = "black"
facet_kws = { sharey = false }
errordim = "instance_idx"
errorbar = "se"
err_kws = { linewidth = 0.5 }

[plots.__include__.mapping]
dr = '$\Delta$ response'
distance = 'Distance ($\mu$m)'
rel_ori = '$\Delta$ ori. pref. (deg)'
cell_type = "Cell type"
loss = "Loss"

[[plots.__include__]]
axes = "space_ori"
query = "distance > 15 and distance < 400"
cuts = { distance = { __array__ = "15:400:15.0" }, rel_ori = [0, 22.5, 67.5, 90.0] }
x = "distance"
hue = "rel_ori"

[[plots.__include__]]
axes = "ori"
query = "distance > 15 and `space[0]`.abs() < 250 and `space[1]`.abs() < 250"
cuts = { rel_ori = { __array__ = "-5:96:10" } }
x = "rel_ori"

