tag_names = ["path", "loss"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/{MODE}" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }
query = "N == 10"
# query = "N == 10 and instance_idx == 0"
# H calculated based on the following:
# PYR, PV, SST, VIP spontaneous firing rates: 0.6, 1.35, 0.682, 0.844 Hz
# Transfer functions: Rectified() for PYR, Ricciardi(scale=1.0, tau=0.01) for PV, Ricciardi(scale=1.0) for SST and VIP
# columns = { Hdv2 = ["cell_type.map(@H) * dv**2", { H = { PYR = 0, PV = 5.6917, SST = 3.7952, VIP = 4.3375 } } ] }
columns = { Hdv2 = ["cell_type.map(@H) * dv**2", { H = { PYR = 0, PV = 7.7634, SST = 3.9271, VIP = 4.4866 } } ], dv = "10 * dv" }  # convert from units of σ = 10mV to mV

[plots]
__ignore__ = ["subset"]

[plots.__matrix__]
x = ["dv", "Hdv2"]
subset = ["nearby", "nearby_all", "all"]

[[plots.__include__]]
name = { __eval__ = "f'{x}_{subset}'" }
func = "displot"
groupby = ["loss"]
hue = "holo_osi"
hue_order = ["low", "high"]
row = "density"
row_order = ["spreadout", "compact"]
col = "cell_type"
# col_order = ["PYR", "PV", "SST", "VIP"]
col_order = ["PV", "SST", "VIP"]
estimator = "mean"
element = "step"
fill = false
common_bins = false
common_norm = false
stat = "density"
# outliers = [0.001, 1]
# outliers = [0.01, 1]
grid = "yzero"
# height = "paper"
height = 1.2
aspect = 1.1
rc_params = "paper"
title_verbosity = 0
# tight_layout = false
# facet_kws = { sharey = false, sharex = false }
# facet_kws = { sharey = false }
# errordim = "instance_idx"
# errorbar = "se"
# err_kws = { linewidth = 0.5 }

[plots.__include__.mapping]
# dv = '$\Delta$ rec. input'
dv = '$\delta v_j$ (mV)'
dr = "Response (ΔF/F)"
Hdv2 = '$H_{jj}\delta v_j^2$ (Hz)'
distance = 'Distance ($\mu$m)'
rel_ori = '$\Delta$ ori. pref. (deg)'
cell_type = "Cell type"
density = "Density"
holo_osi = "Ens. OSI"

[plots.__include__.replace]
spreadout = "Diffuse"
compact = "Compact"
low = "Untuned"
high = "Cotuned"
model = "Model"
data = "Data"

[[plots.__include__]]
x = "dv"
facet_kws = { sharey = false, sharex = false }
outliers = [0.001, 0.999]

[[plots.__include__]]
x = "Hdv2"
log_scale = true
aspect = 0.95
xlim = [3e-8, 1.5]

[[plots.__include__]]
subset = "nearby"
query = "distance > 15 and distance < 75"

[[plots.__include__]]
subset = "nearby_all"
query = "distance < 75"

