tag_names = ["kind", "path", "loss"]

[dataframes.__matrix__]
kind = ["model", "data"]
path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/{MODE}" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }

[[dataframes.__include__]]
kind = "model"
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }
# min_instances = 9

[[dataframes.__include__]]
kind = "data"
func = ["niarb.viz", "sample_df"]
# df = { __call__ = ["pandas", "concat", { __call__ = ["niarb.io", "load_data"], paths = ["data/ensemble_space_ori_xy_data.pkl", "data/ensemble_space_v_ori_xy_data.pkl", "data/single_cell_space_xy_data.pkl"], uncuts = ["distance", "rel_ori"] }] }
# df = { __call__ = ["pandas", "concat", { __call__ = ["niarb.io", "load_data"], paths = ["data/ensemble_space_ori_xy_data.pkl", "data/ensemble_space_v_ori_xy_data.pkl"], uncuts = ["distance", "rel_ori"] }] }
df = { __call__ = ["pandas", "concat", { __call__ = ["niarb.io", "load_data"], paths = ["data/ensemble_space_ori_xy_data.pkl", "data/ensemble_space_v_ori_osi_xy_data.pkl"], uncuts = ["distance", "rel_ori", "osi"] }] }
y = "dr"
yerr = "dr_se"
index = "index"
errorbar = "sd"

[plots]
__ignore__ = ["N", "axes"]

[plots.__matrix__]
# y = ["dr", "dv"]
y = ["dr"]
# N = [1, 10]
N = [10]
# axes = ["mean_nearby", "mean_unperturbed", "space", "ori", "space_ori"]
# axes = ["mean_nearby", "mean_nearby_transpose", "space", "space_ori"]
axes = ["mean_nearby", "mean_nearby_transpose", "space"]

[[plots.__include__]]
name = { __eval__ = "f'{y}_{N}_{axes}'" }
func = "relplot"
kind = "line"
# groupby = "cell_type"
groupby = ["cell_type"]
# row = "loss"
grid = "yzero"
height = "paper"
aspect = 0.8
rc_params = "paper"
title_verbosity = 0
legend_title = false
# facet_kws = { sharey = "row" }
errordim = ["loss", "index"]
# err_kws = { linewidth = 0.5 }

[plots.__include__.mapping]
dr = "Response (ΔF/F)"
dv = '$\delta v_j$'
distance = 'Distance ($\mu$m)'
rel_ori = '$\Delta$ ori. pref. (deg)'
cell_type = "Cell type"
density = "Density"
holo_osi = "Ens. OSI"

[plots.__include__.replace]
spreadout = "Diffuse"
compact = "Compact"
low = "Untuned"
high = "Cotuned"
model = "Model"
data = "Data"

# [[plots.__include__]]
# N = 1
# query = "distance > 15 and N == 1"

[[plots.__include__]]
N = 10
query = "distance > 15 and N == 10 and holo_osi == 'high'"
col = "density"
col_order = ["spreadout", "compact"]
errorbar = "sd"

[[plots.__include__]]
axes = "mean_nearby"
func = "catplot"
kind = "strip"
units = "loss"
s = 4
dodge = true
grid = { __const__ = "None" }
facet_kws = {}
# tick_params = { axis = "x", bottom = false, labeltop = true, labelbottom = false }
# despine = { bottom = true, top = false }
# spine_kws = { top = { position = "zero" } }

[[plots.__include__]]
axes = "mean_nearby_transpose"
func = "catplot"
kind = "strip"
units = "loss"
s = 4
dodge = true
grid = { __const__ = "None" }
facet_kws = {}
# tick_params = { axis = "x", bottom = false, labeltop = true, labelbottom = false }
# despine = { bottom = true, top = false }
# spine_kws = { top = { position = "zero" } }

[[plots.__include__]]
axes = "space"
cuts = { distance = { __array__ = "15:151:15.0" } }
x = "distance"
style = "kind"
style_order = ["model", "data"]

# [[plots.__include__]]
# axes = "space_ori"
# cuts = { distance = { __array__ = "15:151:15.0" }, rel_ori = [0, 22.5, 67.5, 90.0] }
# x = "distance"
# hue = "rel_ori"
# palette = ["#93B8E2", "#46BC99", "#F69CA0"]
# style = "kind"
# style_order = ["model", "data"]
# aspect = 1.0
# tight_layout = false
# 
# [[plots.__include__]]
# N = 1
# axes = "space"
# aspect = 1

[[plots.__include__]]
N = 10
axes = "space"
query = "distance > 15 and N == 10 and (kind == 'model' or rel_ori.isna())"
hue = "holo_osi"
hue_order = ["low", "high"]

# [[plots.__include__]]
# N = 1
# axes = "mean_nearby"
# query = "kind == 'model' and N == 1 and distance > 15 and distance < 75"
# x = "cell_type"
# groupby = "loss"
# 
# [[plots.__include__]]
# N = 1
# axes = "mean_nearby_transpose"
# query = "kind == 'model' and N == 1 and distance > 15 and distance < 75"
# x = "cell_type"
# groupby = "loss"

[[plots.__include__]]
N = 10
axes = "mean_nearby"
query = "kind == 'model' and N == 10 and distance > 15 and distance < 75"
x = "density"
order = ["spreadout", "compact"]
col = { __const__ = "None" }
hue = "holo_osi"
hue_order = ["low", "high"]
statannot = true
statannot_kws = { test = "wilcoxon" }
aspect = 1.3

[[plots.__include__]]
N = 10
axes = "mean_nearby_transpose"
query = "kind == 'model' and N == 10 and distance > 15 and distance < 75"
hue = "density"
hue_order = ["spreadout", "compact"]
col = { __const__ = "None" }
x = "holo_osi"
order = ["low", "high"]
statannot = true
statannot_kws = { test = "wilcoxon" }
aspect = 1.3

# [[plots.__include__]]
# N = 1
# axes = "space_ori"
# # query = "distance > 15 and N == 1 and osi > 0.25"
# query = "distance > 15 and N == 1"
# aspect = 1.2
# 
# [[plots.__include__]]
# N = 10
# axes = "space_ori"
# # query = "distance > 15 and N == 10 and osi > 0.25"
# query = "distance > 15 and N == 10"
# col = "holo_osi"
# col_order = ["low", "high"]
# row = "density"
# row_order = ["spreadout", "compact"]

