import math
import warnings
from collections.abc import Sequence

import torch
from torch import Tensor


def copy_(tensor: Tensor, src: Tensor):
    """Initialize a tensor by copying values from src.

    Args:
        tensor: Tensor to be initialized.
        src: Tensor whose values are copied. src must be broadcastable to tensor.

    """
    with torch.no_grad():
        tensor.copy_(src)


def W_(
    tensor: Tensor,
    std: float,
    bounds: Sequence[float | Sequence] | Tensor,
    mask: Tensor | None = None,
):
    """Initialize a tensor with a truncated normal distribution with mean 0.

    Args:
        tensor: Tensor to be initialized.
        std: Standard deviation of the normal distribution.
        bounds: Lower and upper bounds of the truncated normal distribution. If
            Tensor-like, it must be broadcastable to (*tensor.shape, 2).
        mask: Boolean mask for which elements to initialize with the truncated normal
          distribution. False values are initialized with 0.

    """
    # This implementation is based on torch.nn.init.trunc_normal_,
    # modified to allow different bounds for each element.
    mean = 0.0
    bounds = torch.as_tensor(bounds, device=tensor.device, dtype=tensor.dtype)
    bounds = bounds.broadcast_to((*tensor.shape, 2))
    a, b = bounds[..., 0], bounds[..., 1]

    if (mean < a - 2 * std).any() or (mean > b + 2 * std).any():
        warnings.warn(
            "mean is more than 2 std from [a, b] in nn.init.W_. "
            "The distribution of values may be incorrect."
        )

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values l, u
        bounds = (1.0 + torch.erf(((bounds - mean) / std) / math.sqrt(2.0))) / 2.0

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        uniform_(tensor, 2 * bounds - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.0))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)

        if mask is not None:
            tensor[~mask] = 0.0


def uniform_(
    tensor: Tensor,
    bounds: Sequence[float | Sequence] | Tensor,
    mask: Tensor | None = None,
):
    """Initialize a tensor with values drawn from a uniform distribution.

    Args:
        tensor: Tensor to be initialized.
        bounds: Lower and upper bounds for the uniform distribution. If Tensor-like,
          it must be broadcastable to (*tensor.shape, 2).
        mask: Boolean mask for which elements to initialize with uniform distribution.
          False values are initialized with the lower bound.

    """
    if mask is None:
        mask = torch.ones_like(tensor, dtype=torch.bool)

    bounds = torch.as_tensor(bounds, device=tensor.device, dtype=tensor.dtype)
    bounds = bounds.broadcast_to((*tensor.shape, 2))
    values = torch.distributions.Uniform(
        bounds[..., 0][mask], bounds[..., 1][mask]
    ).sample()

    with torch.no_grad():
        tensor[mask] = values
        tensor[~mask] = bounds[..., 0][~mask]
