tag_names = ["path", "loss"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = "fits", pattern = "*.pt", indices = { __indices__ = { __environ__ = "INDICES" }  } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.dataframe", "from_state_dict"]
dims = { gW = ["Postsynaptic", "Presynaptic"], sigma = ["Postsynaptic", "Presynaptic"], kappa = ["Postsynaptic", "Presynaptic"], vf = ["cell_type"] }
coords = { gW = [["PYR", "PV", "SST", "VIP"], ["PYR", "PV", "SST", "VIP"]], sigma = [["All"], ["PYR", "PV", "SST", "VIP"]], kappa = [["PYR", "PV", "SST", "VIP"], ["PYR", "PV", "SST", "VIP"]], vf = [["PYR", "PV", "SST", "VIP"]] }
state_dict = { __call__ = ["torch", "load"], f = { __eval__ = "path" }, map_location = "cpu", weights_only = true }
columns = { scaled_value = "10 * value" }  # for converting vf and dh from units of σ = 10mV to mV

[plots.__matrix__]
name = ["gW", "sigma", "kappa", "dh", "vf", "hz_to_dff"]

[[plots.__include__]]
func = "catplot"
y = "value"
s = 4
height = "paper"
rc_params = "paper"

[[plots.__include__]]
name = "gW"
query = "variable == 'gW'"
x = "Postsynaptic"
order = ["PYR", "PV", "SST", "VIP"]
col = "Presynaptic"
col_order = ["PYR", "PV", "SST", "VIP"]
grid = "yzero"
mapping = { value = '$g_\alpha |w_{\alpha \beta}|$', Postsynaptic = '$\alpha$', Presynaptic = '$\beta$' }

[[plots.__include__]]
name = "sigma"
query = "variable == 'sigma'"
x = "Presynaptic"
order = ["PYR", "PV", "SST", "VIP"]
aspect = 1.2
mapping = { value = '$\sigma_{\alpha \beta}$ (μm)', Postsynaptic = '$\alpha$', Presynaptic = '$\beta$' }

[[plots.__include__]]
name = "kappa"
query = "variable == 'kappa'"
x = "Postsynaptic"
order = ["PYR", "PV", "SST", "VIP"]
col = "Presynaptic"
col_order = ["PYR", "PV", "SST", "VIP"]
grid = "yzero"
mapping = { value = '$\kappa_{\alpha \beta}$', Postsynaptic = '$\alpha$', Presynaptic = '$\beta$' }

[[plots.__include__]]
name = "dh"
query = "variable == 'dh'"
y = "scaled_value"
mapping = { scaled_value = '$c$ (mV)' }
height = 1.2

[[plots.__include__]]
name = "vf"
query = "variable == 'vf'"
x = "cell_type"
y = "scaled_value"
order = ["PYR", "PV", "SST", "VIP"]
aspect = 1.2
mapping = { value = '$v^*_\alpha$ (mV)', cell_type = '$\alpha$' }

[[plots.__include__]]
name = "hz_to_dff"
query = "variable == 'hz_to_dff'"
mapping = { value = '$\gamma$ ($\Delta$F/F $Hz^{-1}$)' }
height = 1.2
ylim = [1.24, 1.31]  # hard code it for now to get easy-to-read y-axis

