tag_names = ["path"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = "fits", pattern = "*.pt", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
func = ["niarb.dataframe", "from_state_dict"]
dims = { gW = ["Postsynaptic", "Presynaptic"], sigma = ["Postsynaptic", "Presynaptic"], kappa = ["Postsynaptic", "Presynaptic"] }
coords = { gW = [["PYR", "PV", "SST"], ["PYR", "PV", "SST"]], sigma = [["PYR", "PV", "SST"], ["PYR", "PV", "SST"]], kappa = [["PYR", "PV", "SST"], ["PYR", "PV", "SST"]] }
state_dict = { __call__ = ["torch", "load"], f = { __eval__ = "path" }, map_location = "cpu", weights_only = true }

[[plots.__matrix__]]
name = ["gW", "sigma", "kappa", "dh", "vf"]

[[plots.__include__]]
query = { __eval__ = "f\"variable == '{name}'\"" }
func = "displot"
x = "value"
height = 2
element = "step"
fill = false
common_bins = false
facet_kws = { sharex = false }

[[plots.__include__]]
name = "gW"
row = "Postsynaptic"
col = "Presynaptic"
mapping = { value = "Connectivity strength" }

[[plots.__include__]]
name = "sigma"
row = "Postsynaptic"
col = "Presynaptic"
mapping = { value = 'Connectivity width ($\mu$m)' }

[[plots.__include__]]
name = "kappa"
row = "Postsynaptic"
col = "Presynaptic"
mapping = { value = 'Tuning index ($\kappa$)' }

[[plots.__include__]]
name = "dh"
mapping = { value = "Perturbation strength" }

[[plots.__include__]]
name = "vf"
mapping = { value = "Baseline voltage" }

