tag_names = ["path", "loss"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/{MODE}" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }
query = "dh == 0 and distance < 300"

[[plots]]
name = { __format__ = "resp_indiv_units" }
groupby = ["N", "loss", "cell_type"]
reset_index = [-1, "neuron_idx"]
func = "relplot"
kind = "line"
x = "t"
y = "dr"
units = "neuron_idx"
col = "holo_osi"
col_order = ["low", "high"]
row = "density"
row_order = ["spreadout", "compact"]
estimator = { __const__ = "None" }
grid = "yzero"
height = 2
aspect = 1
color = "black"
linewidth = 0.1
facet_kws = { sharey = false }

[plots.mapping]
t = 'time ($\tau$)'
dr = '$\Delta$ response'
distance = 'Distance ($\mu$m)'
rel_ori = '$\Delta$ ori. pref. (deg)'
density = "Density"
holo_osi = "Ensemble OSI"
