tag_names = ["path"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = "fits", pattern = "*.pt", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
func = ["niarb.dataframe", "from_state_dict"]
dims = { gW = ["Postsynaptic", "Presynaptic"], sigma = ["Postsynaptic", "Presynaptic"], kappa = ["Postsynaptic", "Presynaptic"] }
coords = { gW = [["PYR", "PV"], ["PYR", "PV"]], sigma = [["All"], ["PYR", "PV"]], kappa = [["PYR", "PV"], ["PYR", "PV"]] }
state_dict = { __call__ = ["torch", "load"], f = { __eval__ = "path" }, map_location = "cpu", weights_only = true }

[[plots.__include__]]
func = "catplot"
y = "value"
s = 4
height = "paper"
rc_params = "paper"

[[plots.__include__]]
name = "gW"
query = "variable == 'gW'"
x = "Postsynaptic"
order = ["PYR", "PV"]
col = "Presynaptic"
col_order = ["PYR", "PV"]
mapping = { value = '$g_\alpha w_{\alpha \beta}$', Postsynaptic = '$\alpha$', Presynaptic = '$\beta$' }

[[plots.__include__]]
name = "sigma"
query = "variable == 'sigma'"
x = "Presynaptic"
order = ["PYR", "PV"]
aspect = 1.2
mapping = { value = '$\sigma_{\alpha \beta}$ (μm)', Postsynaptic = '$\alpha$', Presynaptic = '$\beta$' }

[[plots.__include__]]
name = "kappa"
query = "variable == 'kappa'"
x = "Postsynaptic"
order = ["PYR", "PV"]
col = "Presynaptic"
col_order = ["PYR", "PV"]
mapping = { value = '$\kappa_{\alpha \beta}$', Postsynaptic = '$\alpha$', Presynaptic = '$\beta$' }

[[plots.__include__]]
name = "dh"
query = "variable == 'dh'"
mapping = { value = '$\delta h$' }

[[plots.__include__]]
name = "vf"
query = "variable == 'vf'"
mapping = { value = '$v^*_\alpha$' }

[[plots.__include__]]
name = "hz_to_dff"
query = "variable == 'hz_to_dff'"
mapping = { value = 'ΔF/F per Hz' }

