tag_names = ["path", "loss"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/matrix_linear_approx_uniform" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }
# path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/linear_approx_uniform" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }
# NOTE: dri = Lij * gj * dhj ==> Lij = dri / (gj * dhj)
# G calculated based on the following:
# Spontaneous firing rate: 0.6 Hz
# Transfer function: Ricciardi(scale=1.0) for PV
columns = { Lij = "dr / (2.2590 * dh.max())" }

[plots.__matrix__]
# name = ["all", "nearby"]
name = ["all"]

[[plots.__include__]]
func = "catplot"
kind = "bar"
x = "perturbed_cell_type"
y = "Lij"
order = ["PYR", "PV"]
col = "loss"
row = "cell_type"
row_order = ["PYR", "PV"]
errorbar = "se"
grid = "yzero"
height = "paper"
# aspect = 1.2
rc_params = "paper"
sharey = false

[plots.__include__.mapping]
Lij = '$L_\mathrm{XY}$'
perturbed_cell_type = "Y"
cell_type = "X"
loss = "Loss"

[plots.__include__.replace]
PYR = "E"
PV = "I"

# [[plots.__include__]]
# name = { __eval__ = "x" }
# groupby = "loss"
# func = "displot"
# row = "perturbed_cell_type"
# row_order = ["PYR", "PV", "SST", "VIP"]
# col = "cell_type"
# col_order = ["PYR", "PV", "SST", "VIP"]
# estimator = "mean"
# element = "step"
# fill = false
# stat = "density"
# grid = "yzero"
# height = "paper"
# aspect = 1.1
# rc_params = "paper"
# title_template = '$L_{{{row_name} \to {col_name}}}$'
# # facet_kws = { sharey = false, sharex = "col" }
# facet_kws = { sharey = false, sharex = false }
# 
# [plots.__include__.mapping]
# Lij = '$L_{ij}$'
# cell_type = "Cell type"
# loss = "Loss"

