tag_names = ["path", "loss"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/{MODE}" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }
# query = "distance == 0"
query = "dh != 0"

[plots]
__ignore__ = ["N"]

[plots.__matrix__]
N = [1, 10]

[[plots.__include__]]
name = { __eval__ = "f'resp_perturbed_{N}'" }
query = { __eval__ = "f'N == {N}'" }
func = "catplot"
kind = "bar"
x = "loss"
y = "dr"
grid = "yzero"
height = 2
aspect = 1
errorbar = "se"

[plots.__include__.mapping]
dr = '$\Delta$ response'
loss = 'Loss'
density = "Density"
holo_osi = "Ensemble OSI"

[[plots.__include__]]
N = 10
row = "density"
row_order = ["spreadout", "compact"]
col = "holo_osi"
col_order = ["low", "high"]

