tag_names = ["path", "loss"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/{MODE}" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }
# query = "N == 10"
query = "N == 10 and instance_idx == 0"
columns = { Hdv2 = "3.4953 * dv**2" }

[plots]
__ignore__ = ["subset"]

[plots.__matrix__]
# subset = ["nearby", "nocenter", "all"]
subset = ["nearby"]

[[plots.__include__]]
name = { __eval__ = "f'joint_{subset}'" }
func = "jointplot"
joint_kind = "line"
x = "dv"
y = "Hdv2"
groupby = ["loss", "cell_type", "density"]
hue = "holo_osi"
hue_order = ["low", "high"]
joint_kws = { legend = false }
marginal_kws = { estimator = "mean", element = "step", fill = false, common_bins = false, common_norm = false, stat="density", linewidth = 0.8 }
ratio = 3
grid = "yzero"
height = "paper"
# aspect = 0.8
rc_params = "paper"
spine_kws = { bottom  = { lw = 0.25 }, left = { lw = 0.25 } }
# spine_kws = { bottom  = { visible = false }, left = { visible = false } }
title_verbosity = 0
tight_layout = false
# facet_kws = { sharey = "row" }
# errordim = "instance_idx"
# errorbar = "se"
# err_kws = { linewidth = 0.5 }

[plots.__include__.mapping]
# dv = '$\Delta$ rec. input'
dv = '$\delta v_j$'
dr = "Response (ΔF/F)"
Hdv2 = '$H_{jj}\delta v_j^2$'
distance = 'Distance ($\mu$m)'
rel_ori = '$\Delta$ ori. pref. (deg)'
cell_type = "Cell type"
density = "Density"
holo_osi = "Ens. OSI"

[plots.__include__.replace]
spreadout = "Diffuse"
compact = "Compact"
low = "Untuned"
high = "Cotuned"
model = "Model"
data = "Data"

[[plots.__include__]]
subset = "nearby"
query = "distance > 15 and distance < 50"

# [[plots.__include__]]
# subset = "nocenter"
# query = "distance > 15"

