batch_size = 1
# dataset = { __ref__ = ["fit.toml", "validation_dataset"] }
# dataset = { __ref__ = ["fit.toml", "validation_dataset"], neurons = { __ref__ = ["fit.toml", "validation_dataset", "neurons"], min_dist = { __call__ = ["builtins", "float", { __environ__ = "MIN_DIST" }] } } }
# dataset = { __ref__ = ["fit.toml", "validation_dataset"], neurons = { __ref__ = ["fit.toml", "validation_dataset", "neurons"], space_extent = [1250.0, 1100.0], N = 40759 } }
# dataset = { __ref__ = ["fit.toml", "validation_dataset"], seed = 1 }
# dataset = { __ref__ = ["fit.toml", "validation_dataset"], model_kwargs = {} }
# dataset = { __ref__ = ["fit.toml", "validation_dataset"], model_kwargs = { t = [1000.0] } }
pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, f = { __call__ = ["niarb.nn", "Ricciardi"], scale = 0.967 } }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, tau = [1.0, 0.5, 2.0] }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, f = "Identity" }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, f = "Identity", simulation_kwargs = { options = { max_num_steps = 100000 }, dx_rtol = 5e-5, max_t = 200.0, max_dxdt = 10000.0 } }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, nonlinear_kwargs = { max_num_steps = 2, assert_convergence = false } }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, nonlinear_kwargs = { max_num_steps = 100, assert_convergence = false } }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, simulation_kwargs = { options = { max_num_steps = 100000 } } }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, simulation_kwargs = { options = { max_num_steps = 100000 }, dx_rtol = 5e-5, max_t = 2000.0 } }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, simulation_kwargs = { options = { max_num_steps = 20000 }, dx_rtol = 1e-4, max_t = 2000.0 } }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, simulation_kwargs = { method = "tsit5", options = { max_num_steps = 100000 }, dx_rtol = 5e-5, max_t = 2000.0 } }
# pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], mode = { __environ__ = "MODE" }, simulation_kwargs = { method = "radauIIA5", options = { step_size = 0.05 }, dx_rtol = 5e-5, max_t = 1000.0 } }

[dataset]
__ref__ = ["fit.toml", "validation_dataset"]

[[dataset.perturbations.configs.__matrix__]]
N = [1]
cell_probs = [{ PYR = 1.0 }]
# space = [["uniform", [550.0, 410.0]]]
space = [["uniform", [500.0, 500.0]]]
osi = [["uniform_", 0.5, 1.0]]
# we need to find the value k
# f(vf'[0] + k * dh') - f(vf'[0]) = 3.0 * (f(vf[0] + dh) - f(vf[0]))
# Since we fitted with a linear model, and f(vf') = vf, we have
# f(vf'[0] + k * dh') - vf[0] = 3.0 * dh. In particular,
# if we assume the fitted dh = 17.58, then since vf[0] = 0.58,
# vf'[0] = -0.1264, and dh' = 1.4132, we get
# k = (finv(52.74 + 0.58) + 0.1264) / 1.4132 = 1.8256
value = [1.8256]
repeats = [5]

[[dataset.perturbations.configs.__matrix__]]
N = [10]
expr = ["""
special.uniform(extents, dspace).prod(dim=-1) * \
special.von_mises(torch.exp(k0 + k1 * osi + k2 * osi**2), dori) * \
special.ubeta(a, b, osi)\
"""]
cell_probs = [{ PYR = 1.0 }]
density = ["spreadout", "compact"]
holo_osi = ["low", "high"]
affine_ori = [true]
repeats = [5]

[dataset.perturbations.mapping]
__ref__ = ["fit.toml", "validation_dataset", "perturbations", "mapping"]

[state_dict]
__call__ = ["niarb.io", "load_state_dict"]
weights_only = true
map_location = "cpu"
# assume fitted dh = 17.58
modify = { dh = [[[], 1.4132]], vf = [[["PYR"], -0.1264]] }

[state_dict.path]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }

[out]
__format__ = "runs/{MODE}_nonlinear_PYR/{filename}.pkl"
# __format__ = "runs/{MODE}_larger/{filename}.pkl"
# __format__ = "runs/{MODE}_seed-1/{filename}.pkl"
# __format__ = "runs/{MODE}_wrapped/{filename}.pkl"
# __format__ = "runs/{MODE}_min_dist-{MIN_DIST}/{filename}.pkl"
# __format__ = "runs/{MODE}-2/{filename}.pkl"
# __format__ = "runs/{MODE}-100/{filename}.pkl"
# __format__ = "runs/{MODE}_linear/{filename}.pkl"
# __format__ = "runs/{MODE}_larger_linear/{filename}.pkl"

[out.filename]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
stem = true
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }

